{% set name = "cache_decorator" %}
{% set version = "2.1.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cache_decorator-{{ version }}.tar.gz
  sha256: 781951788d0e601393ed1a57f39b8883d20b350ebbbfdd1da6581bac50c2e3d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dict_hash >=1.1.32
    - humanize >=3.4.1
    - compress-pickle >=2.0.1
    - compress_json >=1.0.4
    - deflate_dict

test:
  imports:
    - cache_decorator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zommiommy/cache_decorator
  summary: a simple decorator to cache the results of computationally heavy functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
